=== austin-hess/json2apexcli/master-schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "governingLawState": { "type": "string" },
    "transactionDate": { "type": "string" },
    "applicationDate": { "type": "string" },
    "activityType": { "type": "integer" },
    "isCommunityProperty": { "type": "boolean" },
    "applicants": {
      "type": "object",
      "properties": {
        "individuals": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "ID": { "type": "string" },
              "firstName": { "type": "string" },
              "lastName": { "type": "string" },
              "middleName": { "type": "string" },
              "suffixName": { "type": "string" },
              "address": {
                "type": "object",
                "properties": {
                  "primaryAddressLine": { "type": "string" },
                  "city": { "type": "string" },
                  "state": { "type": "string" },
                  "postalCode": { "type": "string" }
                },
                "required": [
                  "city",
                  "postalCode",
                  "primaryAddressLine",
                  "state"
                ]
              },
              "ssn": { "type": "string" },
              "dateOfBirth": { "type": "string" },
              "tinStatus": { "type": "integer" },
              "previousAddresses": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "primaryAddressLine": { "type": "string" },
                    "city": { "type": "string" },
                    "state": { "type": "string" },
                    "postalCode": { "type": "string" }
                  },
                  "required": [
                    "city",
                    "postalCode",
                    "primaryAddressLine",
                    "state"
                  ]
                }
              },
              "employers": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": { "type": "string" },
                    "address": {
                      "type": "object",
                      "properties": {
                        "primaryAddressLine": { "type": "string" },
                        "city": { "type": "string" },
                        "state": { "type": "string" },
                        "postalCode": { "type": "string" }
                      },
                      "required": [
                        "city",
                        "postalCode",
                        "primaryAddressLine",
                        "state"
                      ]
                    },
                    "isSelfEmployment": { "type": "integer" },
                    "lengthOfEmploymentMonths": { "type": "string" }
                  },
                  "required": [
                    "address",
                    "isSelfEmployment",
                    "lengthOfEmploymentMonths",
                    "name"
                  ]
                }
              },
              "previousEmployers": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "name": { "type": "string" },
                    "address": {
                      "type": "object",
                      "properties": {
                        "primaryAddressLine": { "type": "string" },
                        "city": { "type": "string" },
                        "state": { "type": "string" },
                        "postalCode": { "type": "string" }
                      },
                      "required": [
                        "city",
                        "postalCode",
                        "primaryAddressLine",
                        "state"
                      ]
                    },
                    "isSelfEmployment": { "type": "integer" }
                  },
                  "required": ["address", "isSelfEmployment", "name"]
                }
              },
              "identifications": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "description": { "type": "string" },
                    "number": { "type": "string" },
                    "issuer": { "type": "string" },
                    "issueDate": { "type": "string" },
                    "expirationDate": { "type": "string" }
                  },
                  "required": [
                    "description",
                    "expirationDate",
                    "issueDate",
                    "issuer",
                    "number"
                  ]
                }
              },
              "phones": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "type": { "type": "integer" },
                    "number": { "type": "string" }
                  },
                  "required": ["number", "type"]
                }
              },
              "isOFACVerified": { "type": "boolean" },
              "spouseID": { "type": "string" },
              "isPrimaryOwner": { "type": "boolean" },
              "isCIVDocumentRequired": { "type": "boolean" },
              "ATMDebitCard": {
                "type": "object",
                "properties": {
                  "type": { "type": "integer" },
                  "number": { "type": "string" },
                  "cardholderStatus": { "type": "integer" },
                  "cardStatus": { "type": "integer" },
                  "linkedAccounts": {
                    "type": "array",
                    "items": { "type": "string" }
                  }
                },
                "required": [
                  "cardStatus",
                  "cardholderStatus",
                  "linkedAccounts",
                  "number",
                  "type"
                ]
              },
              "attorneysInFact": {
                "type": "array",
                "items": { "type": "string" }
              },
              "isMinor": { "type": "boolean" }
            },
            "required": [
              "ID",
              "address",
              "firstName",
              "lastName",
              "ssn",
              "tinStatus"
            ]
          }
        },
        "businesses": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "ID": { "type": "string" },
              "name": { "type": "string" },
              "entityType": { "type": "integer" },
              "tin": { "type": "string" },
              "parentCompanyIDs": { "type": "string" },
              "dba": { "type": "string" },
              "natureOfBusiness": { "type": "string" },
              "establishedDate": { "type": "string" },
              "isNonProfit": { "type": "boolean" },
              "resolutionOnFileType": { "type": "integer" },
              "principalOfficeState": { "type": "string" },
              "principalOfficeCity": { "type": "string" },
              "address": {
                "type": "object",
                "properties": {
                  "primaryAddressLine": { "type": "string" },
                  "state": { "type": "string" },
                  "city": { "type": "string" },
                  "postalCode": { "type": "string" }
                },
                "required": [
                  "city",
                  "postalCode",
                  "primaryAddressLine",
                  "state"
                ]
              },
              "isEngagesInInternetGambling": { "type": "boolean" },
              "signers": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "ID": { "type": "string" },
                    "firstName": { "type": "string" },
                    "middleName": { "type": "string" },
                    "lastName": { "type": "string" },
                    "suffixName": { "type": "string" },
                    "address": {
                      "type": "object",
                      "properties": {
                        "primaryAddressLine": { "type": "string" },
                        "state": { "type": "string" },
                        "city": { "type": "string" },
                        "postalCode": { "type": "string" }
                      },
                      "required": [
                        "city",
                        "postalCode",
                        "primaryAddressLine",
                        "state"
                      ]
                    },
                    "dateOfBirth": { "type": "string" },
                    "ssn": { "type": "string" },
                    "isDocumentSigner": { "type": "boolean" },
                    "isResolutionSigner": { "type": "boolean" },
                    "isResolutionCertifier": { "type": "boolean" },
                    "isBeneficialOwner": { "type": "boolean" },
                    "isBeneficialOwnerManager": { "type": "boolean" },
                    "isBeneficialOwnerCertifier": { "type": "boolean" },
                    "isTINCertifier": { "type": "boolean" },
                    "capacityDescription": { "type": "string" },
                    "isTrustee": { "type": "boolean" },
                    "isTrustBeneficiary": { "type": "boolean" },
                    "isTrustCreator": { "type": "boolean" }
                  },
                  "required": [
                    "ID",
                    "address",
                    "capacityDescription",
                    "dateOfBirth",
                    "firstName",
                    "isBeneficialOwner",
                    "isBeneficialOwnerCertifier",
                    "isBeneficialOwnerManager",
                    "isTINCertifier",
                    "lastName",
                    "ssn"
                  ]
                }
              }
            },
            "required": [
              "ID",
              "address",
              "dba",
              "entityType",
              "establishedDate",
              "isEngagesInInternetGambling",
              "name",
              "natureOfBusiness",
              "parentCompanyIDs",
              "principalOfficeCity",
              "principalOfficeState",
              "signers",
              "tin"
            ]
          }
        }
      }
    },
    "accounts": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ID": { "type": "integer" },
          "number": { "type": "string" },
          "type": { "type": "integer" },
          "ownershipStructure": { "type": "integer" },
          "ownershipType": { "type": "integer" },
          "primaryOwnerID": { "type": "string" },
          "productCode": { "type": "string" },
          "productDescription": { "type": "string" },
          "owners": { "type": "array", "items": { "type": "string" } },
          "rateStructure": { "type": "integer" },
          "rateType": { "type": "integer" },
          "compoundingFrequency": { "type": "integer" },
          "creditingFrequency": { "type": "integer" },
          "interestPaymentMethod": { "type": "integer" },
          "rates": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "interestRate": { "type": "number" },
                "apy": { "type": "number" }
              },
              "required": ["apy", "interestRate"]
            }
          },
          "depositAmount": { "type": "number" },
          "fiduciaries": { "type": "array", "items": { "type": "string" } },
          "statementMailingAddress": {
            "type": "object",
            "properties": {
              "primaryAddressLine": { "type": "string" },
              "city": { "type": "string" },
              "state": { "type": "string" },
              "postalCode": { "type": "string" }
            },
            "required": ["city", "postalCode", "primaryAddressLine", "state"]
          },
          "authorizedSigners": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "ID": { "type": "string" },
                "isDurable": { "type": "boolean" }
              },
              "required": ["ID", "isDurable"]
            }
          },
          "beneficiaries": { "type": "array", "items": { "type": "string" } },
          "safeDepositBox": {
            "type": "object",
            "properties": {
              "size": { "type": "string" },
              "numberOfKeys": { "type": "integer" },
              "numberOfRequiredRentersToAccess": { "type": "integer" },
              "deputies": { "type": "array", "items": { "type": "string" } },
              "appointees": { "type": "array", "items": { "type": "string" } }
            },
            "required": [
              "appointees",
              "deputies",
              "numberOfKeys",
              "numberOfRequiredRentersToAccess",
              "size"
            ]
          },
          "custodians": { "type": "array", "items": { "type": "string" } },
          "successorCustodians": {
            "type": "array",
            "items": { "type": "string" }
          }
        },
        "required": [
          "ID",
          "number",
          "owners",
          "ownershipStructure",
          "primaryOwnerID",
          "productCode",
          "productDescription",
          "type"
        ]
      }
    },
    "financialInstitution": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "address": {
          "type": "object",
          "properties": {
            "primaryAddressLine": { "type": "string" },
            "city": { "type": "string" },
            "state": { "type": "string" },
            "postalCode": { "type": "string" }
          },
          "required": ["city", "postalCode", "primaryAddressLine", "state"]
        },
        "decisionOfficer": {
          "type": "object",
          "properties": {
            "name": { "type": "string" },
            "title": { "type": "string" }
          },
          "required": ["name", "title"]
        },
        "documentSigner": {
          "type": "object",
          "properties": {
            "name": { "type": "string" },
            "title": { "type": "string" }
          },
          "required": ["name", "title"]
        },
        "documentPreparer": {
          "type": "object",
          "properties": {
            "name": { "type": "string" },
            "title": { "type": "string" }
          },
          "required": ["name", "title"]
        },
        "openingBranch": {
          "type": "object",
          "properties": {
            "name": { "type": "string" },
            "code": { "type": "string" },
            "address": {
              "type": "object",
              "properties": {
                "primaryAddressLine": { "type": "string" },
                "city": { "type": "string" },
                "state": { "type": "string" },
                "postalCode": { "type": "string" }
              },
              "required": ["city", "postalCode", "primaryAddressLine", "state"]
            }
          },
          "required": ["address", "code", "name"]
        }
      },
      "required": [
        "address",
        "decisionOfficer",
        "documentPreparer",
        "documentSigner",
        "name",
        "openingBranch"
      ]
    },
    "contacts": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ID": { "type": "string" },
          "entityType": { "type": "string" },
          "firstName": { "type": "string" },
          "lastName": { "type": "string" },
          "businessName": { "type": "string" },
          "title": { "type": "string" },
          "address": {
            "type": "object",
            "properties": {
              "primaryAddressLine": { "type": "string" },
              "city": { "type": "string" },
              "state": { "type": "string" },
              "postalCode": { "type": "string" }
            },
            "required": ["city", "postalCode", "primaryAddressLine", "state"]
          }
        },
        "required": [
          "ID",
          "address",
          "businessName",
          "entityType",
          "firstName",
          "lastName",
          "title"
        ]
      }
    }
  },
  "required": [
    "accounts",
    "activityType",
    "applicants",
    "applicationDate",
    "financialInstitution",
    "governingLawState",
    "transactionDate"
  ]
}

=== austin-hess/json2apexcli/Deposit_UC2_OpenChecking_Joint_FundTfr_Bene_DebitCard.json
{
	"governingLawState": "TX",
	"transactionDate": "11/02/2020",
  "applicationDate": "10/15/2020",
  "activityType": 1,
  "isCommunityProperty": false,
	"applicants": {
		"individuals": [
			{
        "ID": "123456",
				"firstName": "Sharon",
				"lastName": "Smith",
				"middleName": "Marie",
        "suffixName": "",
				"address": {
					"primaryAddressLine": "999 Autumn St",
					"city": "Austin",
					"state": "TX",
					"postalCode": "49546"
				},
        "ssn": "123555999",
        "tinStatus": 6,
				"previousAddresses": [
					{
						"primaryAddressLine": "123 Last St",
						"city": "Austin",
						"state": "TX",
						"postalCode": "49546"
					}
				],
				"employers": [
					{
						"name": "ABC Plumbing",
						"address": {
							"primaryAddressLine": "555 Plumbing St",
							"city": "Austin",
							"state": "TX",
							"postalCode": "49546"
						},
						"isSelfEmployment": 0,
						"lengthOfEmploymentMonths": "52"
					}
				],
				"previousEmployers": [
					{
						"name": "XYZ Plumbing",
						"address": {
							"primaryAddressLine": "123 Main St",
							"city": "Austin",
							"state": "TX",
							"postalCode": "49546"
						},
						"isSelfEmployment": 0
					}
				],
        "identifications": [
          {
            "description": "Drivers License",
            "number": "XZ56654546",
            "issuer": "State of Michigan",
            "issueDate": "05/01/2019",
            "expirationDate": "05/01/2022"
          },
          {
            "description": "Military ID",
            "number": "998798797",
            "issuer": "U.S. Space Force",
            "issueDate": "10/01/2019",
            "expirationDate": "10/01/2022"
          }
        ],
        "phones": [
          {
            "type": 1,
            "number": "360-555-7899"
          },
          {
            "type": 2,
            "number": "360-123-1238"
          }
        ],
        "isOFACVerified": false,
        "spouseID": "987655",
        "ATMDebitCard": {
            "type": 2,
            "number": "4145222266669999",
            "cardholderStatus": 2,
            "cardStatus": 1,
            "linkedAccounts": [
              "516511"
            ]
        }
			},
      {
        "ID": "987655",
        "isPrimaryOwner": false,
        "firstName": "John",
        "middleName": "Edward",
        "lastName": "Smith",
        "suffixName": "Jr",
        "ssn": "123777777",
        "tinStatus": 6,
        "spouseID": "123456",
        "address": {
          "primaryAddressLine": "999 Autumn St",
          "city": "Austin",
          "state": "TX",
          "postalCode": "49546"
        },
        "previousAddresses": [
          {
            "primaryAddressLine": "123 Last St",
            "city": "Austin",
            "state": "TX",
            "postalCode": "49546"
          }
        ],
        "ATMDebitCard": {
          "type": 2,
          "number": "4145222266668888",
          "cardholderStatus": 2,
          "cardStatus": 1,
          "linkedAccounts": [
            "516511"
          ]
        }
      }
		]
	},
  "contacts": [
    {
      "ID": "654222",
      "entityType": "",
      "firstName": "Joseph",
      "lastName": "Baker",
      "businessName": "",
      "title": "Beneficiary",
      "address": {
        "primaryAddressLine": "123 Baker",
        "city": "Austin",
        "state": "TX",
        "postalCode": "49546"
      }
    },
    {
      "ID": "654339",
      "entityType": "",
      "firstName": "Aliyah",
      "lastName": "Baker",
      "businessName": "",
      "title": "Beneficiary",
      "address": {
        "primaryAddressLine": "123 Baker",
        "city": "Austin",
        "state": "TX",
        "postalCode": "49546"
      }
    }
  ],
	"accounts": [
    {
      "ID": 516511,
      "number": "54654444",
      "type": 1,
      "ownershipStructure": 2,
      "ownershipType": 17,
      "primaryOwnerID": "123456",
      "productCode": "BasicChecking",
      "productDescription": "Basic Checking",
      "owners": [
        "123456",
        "987655"
      ],
      "depositAmount": 10000.00,
      "beneficiaries": [
        "654222",
        "654339"
      ],
      "statementMailingAddress": {
        "primaryAddressLine": "999 Autumn St",
        "city": "Austin",
        "state": "NC",
        "postalCode": "49546"
      }
    }
	],
	"financialInstitution": {
		"name": "CS Bank",
		"address": {
			"primaryAddressLine": "12345 Bank Ave",
			"city": "Austin",
			"state": "TX",
			"postalCode": "49546"
		},
		"decisionOfficer": {
			"name": "Bill Thomas",
			"title": "Sr. Underwriter"
		},
		"documentSigner": {
			"name": "Aliyah Brown",
			"title": "Branch Manager"
		},
		"documentPreparer": {
			"name": "Aliyah Brown",
			"title": "Branch Manager"
		},
		"openingBranch": {
			"name": "Waterworks",
			"code": "X5555",
			"address": {
				"primaryAddressLine": "123 Branch St.",
				"city": "Austin",
				"state": "TX",
				"postalCode": "49546"
			}
		}
	}
}

=== austin-hess/json2apexcli/Deposit_UC26_OpenSavings_ConvenienceSigner.json
{
	"governingLawState": "TX",
	"transactionDate": "11/02/2020",
  "applicationDate": "10/15/2020",
  "activityType": 1,
  "isCommunityProperty": false,
	"applicants": {
		"individuals": [
      {
        "ID": "123456",
        "firstName": "Sharon",
        "lastName": "Smith",
        "middleName": "Marie",
        "suffixName": "",
        "address": {
          "primaryAddressLine": "999 Autumn St",
          "city": "Austin",
          "state": "TX",
          "postalCode": "49546"
        },
        "ssn": "123555999",
        "dateOfBirth": "11/03/1960",
        "tinStatus": 6,
        "previousAddresses": [
          {
            "primaryAddressLine": "123 Last St",
            "city": "Austin",
            "state": "TX",
            "postalCode": "49546"
          }
        ],
        "employers": [
          {
            "name": "ABC Plumbing",
            "address": {
              "primaryAddressLine": "555 Plumbing St",
              "city": "Austin",
              "state": "TX",
              "postalCode": "49546"
            },
            "isSelfEmployment": 0,
            "lengthOfEmploymentMonths": "52"
          }
        ],
        "previousEmployers": [
          {
            "name": "XYZ Plumbing",
            "address": {
              "primaryAddressLine": "123 Main St",
              "city": "Austin",
              "state": "TX",
              "postalCode": "49546"
            },
            "isSelfEmployment": 0
          }
        ],
        "identifications": [
          {
            "description": "Drivers License",
            "number": "XZ56654546",
            "issuer": "State of Michigan",
            "issueDate": "05/01/2019",
            "expirationDate": "05/01/2022"
          },
          {
            "description": "Military ID",
            "number": "998798797",
            "issuer": "U.S. Space Force",
            "issueDate": "10/01/2019",
            "expirationDate": "10/01/2022"
          }
        ],
        "phones": [
          {
            "type": 1,
            "number": "360-555-7899"
          },
          {
            "type": 2,
            "number": "360-123-1238"
          }
        ],
        "isOFACVerified": false,
        "spouseID": "987655"
      }
		]
	},
	"contacts": [
		{
			"ID": "654222",
      "entityType": "",
      "firstName": "Sarah",
      "lastName": "Signer",
      "businessName": "",
      "title": "Convenience Signer",
			"address": {
				"primaryAddressLine": "123 Sarah",
				"city": "Austin",
				"state": "TX",
				"postalCode": "49546"
			}
		}
	],
	"accounts": [
    {
      "ID": 516511,
      "number": "54654444",
      "type": 1,
      "ownershipStructure": 4,
      "primaryOwnerID": "123456",
      "productCode": "GoldSav",
      "productDescription": "Gold Savings",
      "owners": [
        "123456"
      ],
      "rateStructure": 1,
      "rateType": 2,
      "compoundingFrequency": 3,
      "creditingFrequency": 3,
      "interestPaymentMethod": 1,
      "rates": [
        {
          "interestRate": 0.85,
          "apy": 0.86
        }
      ],
      "depositAmount": 10000.00,
      "authorizedSigners": [
        {
          "ID": "654222",
          "isDurable": false
        }
      ]
    }
	],
	"financialInstitution": {
		"name": "CS Bank",
		"address": {
			"primaryAddressLine": "12345 Bank Ave",
			"city": "Austin",
			"state": "TX",
			"postalCode": "49546"
		},
		"decisionOfficer": {
			"name": "Bill Thomas",
			"title": "Sr. Underwriter"
		},
		"documentSigner": {
			"name": "Aliyah Brown",
			"title": "Branch Manager"
		},
		"documentPreparer": {
			"name": "Aliyah Brown",
			"title": "Branch Manager"
		},
		"openingBranch": {
			"name": "Waterworks",
			"code": "X5555",
			"address": {
				"primaryAddressLine": "123 Branch St.",
				"city": "Austin",
				"state": "TX",
				"postalCode": "49546"
			}
		}
	}
}

=== austin-hess/json2apexcli/Deposit_UC4_OpenSavings_Estate.json
{
	"governingLawState": "MI",
	"transactionDate": "11/02/2020",
  "applicationDate": "10/15/2020",
  "activityType": 1,
	"applicants": {
    "businesses": [
      {
        "ID": "987654",
        "name": "Smith Family Estate",
        "entityType": 12,
        "tin": "123456789",
        "parentCompanyIDs": "",
        "dba": "",
        "natureOfBusiness": "",
        "establishedDate": "09/15/2001",
        "principalOfficeState": "MI",
        "principalOfficeCity": "Grand Rapids",
        "address": {
          "primaryAddressLine": "123 Main St.",
          "state": "MI",
          "city": "Grand Rapids",
          "postalCode": "49546"
        },
        "isEngagesInInternetGambling": false,
        "signers": [
          {
            "ID": "55555",
            "firstName": "Jim",
            "middleName": "James",
            "lastName": "Smith",
            "suffixName": "Jr",
            "address": {
              "primaryAddressLine": "123 Test St.",
              "state": "MI",
              "city": "Grand Rapids",
              "postalCode": "49546"
            },
            "dateOfBirth": "06/03/1954",
            "ssn": "555666777",
            "isDocumentSigner": true,
            "isResolutionSigner": false,
            "isResolutionCertifier": false,
            "isBeneficialOwner": false,
            "isBeneficialOwnerManager": false,
            "isBeneficialOwnerCertifier": false,
            "isTINCertifier": true,
            "capacityDescription": "Fiduciary Appointee"
          }
        ]
      }
    ]
	},
	"accounts": [
    {
      "ID": 516511,
      "number": "54654444",
      "type": 1,
      "ownershipStructure": 1,
      "primaryOwnerID": "987654",
      "productCode": "GoldSav",
      "productDescription": "Gold Savings",
      "owners": [
        "987654"
      ],
      "rateStructure": 1,
      "rateType": 2,
      "compoundingFrequency": 3,
      "creditingFrequency": 3,
      "interestPaymentMethod": 1,
      "rates": [
        {
          "interestRate": 0.85,
          "apy": 0.86
        }
      ],
      "depositAmount": 10000.00,
      "statementMailingAddress": {
        "primaryAddressLine": "999 Autumn St",
        "city": "Austin",
        "state": "NC",
        "postalCode": "49546"
      }
    }
	],
	"financialInstitution": {
		"name": "CS Bank",
		"address": {
			"primaryAddressLine": "12345 Bank Ave",
			"city": "Grand Rapids",
			"state": "MI",
			"postalCode": "49546"
		},
		"decisionOfficer": {
			"name": "Bill Thomas",
			"title": "Sr. Underwriter"
		},
		"documentSigner": {
			"name": "Aliyah Brown",
			"title": "Branch Manager"
		},
		"documentPreparer": {
			"name": "Aliyah Brown",
			"title": "Branch Manager"
		},
		"openingBranch": {
			"name": "Waterworks",
			"code": "X5555",
			"address": {
				"primaryAddressLine": "123 Branch St.",
				"city": "Grand Rapids",
				"state": "MI",
				"postalCode": "49546"
			}
		}
	}
}
